name: Repository setup
description: Setup Node.js and perform yarn install

runs:
  using: composite
  steps:
    - name: Setup Node.js version
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Restore yarn cache
      uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile
